version: '3'

services:
  proxysql:
    image: proxysql/proxysql:2.5.3
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
      - ./proxysql:/var/lib/proxysql
    ports:
      # - '6032:6032'
      - '6033:6033'
#      - '6080:6080'
